const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./models/Product');
const connectDB = require('./config/db');

dotenv.config();

const products = [
    {
        id: "peanut-ladoo",
        name_en: "Peanut Ladoo",
        name_ta: "வேர்க்கடலை உருண்டை",
        category: "sweets",
        basePrice: 250,
        description_en: "Traditional peanut ladoos made with roasted groundnuts and jaggery. A perfect blend of crunch and sweetness.",
        description_ta: "வறுத்த வேர்க்கடலை மற்றும் வெல்லத்துடன் தயாரிக்கப்படும் பாரம்பரிய வேர்க்கடலை உருண்டைகள்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Roasted Peanuts", "Jaggery", "Cardamom", "Ghee"],
        ingredients_ta: ["வறுத்த வேர்க்கடலை", "வெல்லம்", "ஏலக்காய்", "நெய்"],
        benefits_en: ["Rich in protein", "Good source of healthy fats", "Natural sweetener used", "No artificial preservatives"],
        benefits_ta: ["புரதம் நிறைந்தது", "ஆரோக்கியமான கொழுப்புகளின் நல்ல ஆதாரம்", "இயற்கை இனிப்பு பயன்படுத்தப்படுகிறது", "செயற்கை பதப்படுத்திகள் இல்லை"],
        storage_en: "Store in an airtight container at room temperature. Keep away from moisture.",
        storage_ta: "அறை வெப்பநிலையில் காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "15-20 days",
        available: true,
        weightOptions: [{ weight: "250g", price: 250, unit: "g" }, { weight: "500g", price: 480, unit: "g" }, { weight: "1kg", price: 920, unit: "g" }]
    },
    {
        id: "black-sesame-ladoo",
        name_en: "Black Sesame Ladoo",
        name_ta: "கருப்பு எள் உருண்டை",
        category: "sweets",
        basePrice: 280,
        description_en: "Nutritious black sesame ladoos packed with iron and calcium. A healthy traditional sweet.",
        description_ta: "இரும்பு மற்றும் கால்சியம் நிறைந்த சத்தான கருப்பு எள் உருண்டைகள்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Black Sesame Seeds", "Jaggery", "Cardamom", "Dry Ginger"],
        ingredients_ta: ["கருப்பு எள்", "வெல்லம்", "ஏலக்காய்", "சுக்கு"],
        benefits_en: ["High in iron and calcium", "Good for bone health", "Rich in antioxidants", "Boosts immunity"],
        benefits_ta: ["இரும்பு மற்றும் கால்சியம் அதிகம்", "எலும்பு ஆரோக்கியத்திற்கு நல்லது", "ஆன்டிஆக்ஸிடன்ட்கள் நிறைந்தது", "நோய் எதிர்ப்பு சக்தியை அதிகரிக்கும்"],
        storage_en: "Store in a cool, dry place in an airtight container.",
        storage_ta: "காற்று புகாத கொள்கலனில் குளிர்ந்த, உலர்ந்த இடத்தில் சேமிக்கவும்.",
        shelfLife: "20-25 days",
        available: true,
        weightOptions: [{ weight: "250g", price: 280, unit: "g" }, { weight: "500g", price: 540, unit: "g" }, { weight: "1kg", price: 1050, unit: "g" }]
    },
    {
        id: "urad-dal-ladoo",
        name_en: "Urad Dal Ladoo",
        name_ta: "உளுந்து உருண்டை",
        category: "sweets",
        basePrice: 300,
        description_en: "Protein-rich urad dal ladoos made with roasted black gram and pure ghee. A winter delicacy.",
        description_ta: "வறுத்த உளுந்து மற்றும் தூய நெய்யுடன் தயாரிக்கப்படும் புரதம் நிறைந்த உளுந்து உருண்டைகள்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Urad Dal", "Sugar", "Ghee", "Cardamom", "Cashews"],
        ingredients_ta: ["உளுந்து", "சர்க்கரை", "நெய்", "ஏலக்காய்", "முந்திரி"],
        benefits_en: ["High protein content", "Good for muscle building", "Provides warmth in winter", "Rich in B vitamins"],
        benefits_ta: ["அதிக புரத உள்ளடக்கம்", "தசை வளர்ச்சிக்கு நல்லது", "குளிர்காலத்தில் வெப்பத்தை அளிக்கிறது", "பி வைட்டமின்கள் நிறைந்தது"],
        storage_en: "Keep refrigerated for longer shelf life.",
        storage_ta: "நீண்ட ஆயுளுக்கு குளிர்சாதன பெட்டியில் வைக்கவும்.",
        shelfLife: "10-15 days (refrigerated: 30 days)",
        available: true,
        weightOptions: [{ weight: "250g", price: 300, unit: "g" }, { weight: "500g", price: 580, unit: "g" }, { weight: "1kg", price: 1120, unit: "g" }]
    },
    {
        id: "mysore-pak",
        name_en: "Mysore Pak",
        name_ta: "மைசூர் பாக்",
        category: "sweets",
        basePrice: 350,
        description_en: "Authentic Mysore Pak made with generous amounts of ghee and gram flour. Melt-in-your-mouth goodness.",
        description_ta: "தாராளமான நெய் மற்றும் கடலை மாவுடன் தயாரிக்கப்படும் உண்மையான மைசூர் பாக்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Gram Flour (Besan)", "Pure Ghee", "Sugar", "Cardamom"],
        ingredients_ta: ["கடலை மாவு", "தூய நெய்", "சர்க்கரை", "ஏலக்காய்"],
        benefits_en: ["Energy booster", "Made with pure ghee", "Traditional recipe", "Perfect for festivals"],
        benefits_ta: ["ஆற்றல் அதிகரிப்பான்", "தூய நெய்யில் தயாரிக்கப்பட்டது", "பாரம்பரிய செய்முறை", "திருவிழாக்களுக்கு ஏற்றது"],
        storage_en: "Store in an airtight container. Best consumed within two weeks.",
        storage_ta: "காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "15-20 days",
        available: true,
        weightOptions: [{ weight: "250g", price: 350, unit: "g" }, { weight: "500g", price: 680, unit: "g" }, { weight: "1kg", price: 1320, unit: "g" }]
    },
    {
        id: "traditional-ladoo",
        name_en: "Traditional Ladoo",
        name_ta: "பாரம்பரிய லட்டு",
        category: "sweets",
        basePrice: 220,
        description_en: "Classic boondi ladoo made with love using traditional methods. Perfect for all occasions.",
        description_ta: "பாரம்பரிய முறைகளைப் பயன்படுத்தி அன்புடன் தயாரிக்கப்படும் கிளாசிக் பூந்தி லட்டு.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Gram Flour", "Sugar Syrup", "Ghee", "Cardamom", "Raisins", "Cashews"],
        ingredients_ta: ["கடலை மாவு", "சர்க்கரை பாகு", "நெய்", "ஏலக்காய்", "திராட்சை", "முந்திரி"],
        benefits_en: ["Festive favorite", "Made fresh to order", "No artificial colors", "Traditional taste"],
        benefits_ta: ["திருவிழா விருப்பமானது", "ஆர்டருக்கு புதிதாக தயாரிக்கப்படுகிறது", "செயற்கை வண்ணங்கள் இல்லை", "பாரம்பரிய சுவை"],
        storage_en: "Store at room temperature in an airtight container.",
        storage_ta: "காற்று புகாத கொள்கலனில் அறை வெப்பநிலையில் சேமிக்கவும்.",
        shelfLife: "20-25 days",
        available: true,
        weightOptions: [{ weight: "250g", price: 220, unit: "g" }, { weight: "500g", price: 420, unit: "g" }, { weight: "1kg", price: 800, unit: "g" }]
    },
    {
        id: "mixture",
        name_en: "Mixture",
        name_ta: "மிக்ஸர்",
        category: "snacks",
        basePrice: 180,
        description_en: "Crispy South Indian mixture with the perfect blend of spices. A tea-time favorite.",
        description_ta: "சரியான மசாலா கலவையுடன் மொறுமொறுப்பான தென்னிந்திய மிக்ஸர்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Rice Flakes", "Peanuts", "Curry Leaves", "Chilli", "Salt", "Oil"],
        ingredients_ta: ["அவல்", "வேர்க்கடலை", "கறிவேப்பிலை", "மிளகாய்", "உப்பு", "எண்ணெய்"],
        benefits_en: ["Crunchy texture", "Perfect snacking option", "Made with fresh spices", "No MSG added"],
        benefits_ta: ["மொறுமொறுப்பான அமைப்பு", "சரியான சிற்றுண்டி விருப்பம்", "புதிய மசாலாக்களுடன் தயாரிக்கப்பட்டது", "MSG சேர்க்கப்படவில்லை"],
        storage_en: "Store in an airtight container to maintain crispiness.",
        storage_ta: "மொறுமொறுப்பை பராமரிக்க காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "30-45 days",
        available: true,
        weightOptions: [{ weight: "250g", price: 180, unit: "g" }, { weight: "500g", price: 350, unit: "g" }, { weight: "1kg", price: 680, unit: "g" }]
    },
    {
        id: "murukku",
        name_en: "Murukku",
        name_ta: "முறுக்கு",
        category: "snacks",
        basePrice: 200,
        description_en: "Authentic hand-pressed murukku made with rice flour and urad dal. Perfectly crunchy and flavorful.",
        description_ta: "அரிசி மாவு மற்றும் உளுந்துடன் கையால் அழுத்தப்பட்ட உண்மையான முறுக்கு.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Rice Flour", "Urad Dal Flour", "Butter", "Cumin", "Sesame Seeds", "Salt"],
        ingredients_ta: ["அரிசி மாவு", "உளுந்து மாவு", "வெண்ணெய்", "சீரகம்", "எள்", "உப்பு"],
        benefits_en: ["Handmade with love", "Traditional recipe", "Perfect crunch", "Great with tea or coffee"],
        benefits_ta: ["அன்புடன் கையால் தயாரிக்கப்பட்டது", "பாரம்பரிய செய்முறை", "சரியான மொறுமொறுப்பு", "தேநீர் அல்லது காபியுடன் சிறந்தது"],
        storage_en: "Keep in an airtight container at room temperature.",
        storage_ta: "அறை வெப்பநிலையில் காற்று புகாத கொள்கலனில் வைக்கவும்.",
        shelfLife: "30-45 days",
        available: true,
        weightOptions: [{ weight: "250g", price: 200, unit: "g" }, { weight: "500g", price: 380, unit: "g" }, { weight: "1kg", price: 740, unit: "g" }]
    },
    {
        id: "pirandai-thokku",
        name_en: "Pirandai Thokku",
        name_ta: "பிரண்டை தொக்கு",
        category: "pickles",
        basePrice: 150,
        description_en: "Traditional pirandai thokku known for its digestive and bone-strengthening properties.",
        description_ta: "செரிமான மற்றும் எலும்பு வலுப்படுத்தும் பண்புகளுக்கு பெயர் பெற்ற பாரம்பரிய பிரண்டை தொக்கு.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Pirandai (Veldt Grape)", "Tamarind", "Chilli", "Salt", "Sesame Oil"],
        ingredients_ta: ["பிரண்டை", "புளி", "மிளகாய்", "உப்பு", "நல்லெண்ணெய்"],
        benefits_en: ["Aids digestion", "Good for bones", "Rich in calcium", "Traditional medicine properties"],
        benefits_ta: ["செரிமானத்திற்கு உதவுகிறது", "எலும்புகளுக்கு நல்லது", "கால்சியம் நிறைந்தது", "பாரம்பரிய மருத்துவ பண்புகள்"],
        storage_en: "Refrigerate after opening. Use clean, dry spoon.",
        storage_ta: "திறந்த பிறகு குளிர்சாதன பெட்டியில் வைக்கவும்.",
        shelfLife: "3-4 months (refrigerated)",
        available: true,
        weightOptions: [{ weight: "200g", price: 150, unit: "g" }, { weight: "400g", price: 280, unit: "g" }, { weight: "1kg", price: 680, unit: "g" }]
    },
    {
        id: "tomato-thokku",
        name_en: "Tomato Thokku",
        name_ta: "தக்காளி தொக்கு",
        category: "pickles",
        basePrice: 120,
        description_en: "Tangy and spicy tomato thokku made with fresh tomatoes and aromatic spices.",
        description_ta: "புதிய தக்காளி மற்றும் நறுமண மசாலாக்களுடன் தயாரிக்கப்படும் தக்காளி தொக்கு.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Fresh Tomatoes", "Red Chilli", "Garlic", "Fenugreek", "Mustard", "Sesame Oil"],
        ingredients_ta: ["புதிய தக்காளி", "சிவப்பு மிளகாய்", "பூண்டு", "வெந்தயம்", "கடுகு", "நல்லெண்ணெய்"],
        benefits_en: ["Rich in lycopene", "No preservatives", "Homemade freshness", "Versatile condiment"],
        benefits_ta: ["லைகோபீன் நிறைந்தது", "பதப்படுத்திகள் இல்லை", "வீட்டு புத்துணர்ச்சி", "பல்துறை சைட் டிஷ்"],
        storage_en: "Store in refrigerator. Always use clean, dry spoon.",
        storage_ta: "குளிர்சாதன பெட்டியில் சேமிக்கவும்.",
        shelfLife: "2-3 months (refrigerated)",
        available: true,
        weightOptions: [{ weight: "200g", price: 120, unit: "g" }, { weight: "400g", price: 220, unit: "g" }, { weight: "1kg", price: 520, unit: "g" }]
    },
    {
        id: "abc-malt",
        name_en: "Apple Beetroot Carrot (ABC) Malt",
        name_ta: "ஆப்பிள் பீட்ரூட் கேரட் மால்ட்",
        category: "malts",
        basePrice: 280,
        description_en: "Nutritious ABC malt made with apple, beetroot, and carrot. Perfect health drink.",
        description_ta: "ஆப்பிள், பீட்ரூட் மற்றும் கேரட்டுடன் தயாரிக்கப்படும் சத்தான ABC மால்ட்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Apple", "Beetroot", "Carrot", "Jaggery", "Cardamom", "Dry Fruits"],
        ingredients_ta: ["ஆப்பிள்", "பீட்ரூட்", "கேரட்", "வெல்லம்", "ஏலக்காய்", "உலர் பழங்கள்"],
        benefits_en: ["Rich in vitamins A, C, and iron", "Boosts immunity", "Good for skin health", "Natural energy booster"],
        benefits_ta: ["வைட்டமின் A, C மற்றும் இரும்பு நிறைந்தது", "நோய் எதிர்ப்பு சக்தியை அதிகரிக்கும்", "தோல் ஆரோக்கியத்திற்கு நல்லது", "இயற்கை ஆற்றல் அதிகரிப்பான்"],
        storage_en: "Store in an airtight container in a cool, dry place.",
        storage_ta: "குளிர்ந்த, உலர்ந்த இடத்தில் காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "3 months",
        available: true,
        weightOptions: [{ weight: "250g", price: 280, unit: "g" }, { weight: "500g", price: 540, unit: "g" }, { weight: "1kg", price: 1050, unit: "g" }]
    },
    {
        id: "beetroot-malt",
        name_en: "Beetroot Malt",
        name_ta: "பீட்ரூட் மால்ட்",
        category: "malts",
        basePrice: 250,
        description_en: "Pure beetroot malt powder for improved blood circulation and stamina.",
        description_ta: "மேம்படுத்தப்பட்ட இரத்த ஓட்டம் மற்றும் சகிப்புத்தன்மைக்கான தூய பீட்ரூட் மால்ட் பொடி.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Beetroot", "Jaggery", "Cardamom", "Almonds"],
        ingredients_ta: ["பீட்ரூட்", "வெல்லம்", "ஏலக்காய்", "பாதாம்"],
        benefits_en: ["Improves hemoglobin", "Rich in iron and folate", "Natural blood purifier", "Boosts stamina"],
        benefits_ta: ["ஹீமோகுளோபினை மேம்படுத்துகிறது", "இரும்பு மற்றும் ஃபோலேட் நிறைந்தது", "இயற்கை இரத்த சுத்திகரிப்பான்", "சகிப்புத்தன்மையை அதிகரிக்கும்"],
        storage_en: "Store in an airtight container away from moisture.",
        storage_ta: "ஈரப்பதத்திலிருந்து விலக்கி காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "3 months",
        available: true,
        weightOptions: [{ weight: "250g", price: 250, unit: "g" }, { weight: "500g", price: 480, unit: "g" }, { weight: "1kg", price: 920, unit: "g" }]
    },
    {
        id: "carrot-malt",
        name_en: "Carrot Malt",
        name_ta: "கேரட் மால்ட்",
        category: "malts",
        basePrice: 240,
        description_en: "Delicious carrot malt for healthy eyes and glowing skin. Perfect for growing children.",
        description_ta: "ஆரோக்கியமான கண்கள் மற்றும் ஒளிரும் சருமத்திற்கான சுவையான கேரட் மால்ட்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Carrot", "Jaggery", "Cardamom", "Cashews"],
        ingredients_ta: ["கேரட்", "வெல்லம்", "ஏலக்காய்", "முந்திரி"],
        benefits_en: ["Rich in Vitamin A", "Good for eyesight", "Improves skin health", "Natural antioxidant"],
        benefits_ta: ["வைட்டமின் A நிறைந்தது", "பார்வைக்கு நல்லது", "தோல் ஆரோக்கியத்தை மேம்படுத்துகிறது", "இயற்கை ஆன்டிஆக்ஸிடன்ட்"],
        storage_en: "Store in an airtight container in a cool place.",
        storage_ta: "குளிர்ந்த இடத்தில் காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "3 months",
        available: true,
        weightOptions: [{ weight: "250g", price: 240, unit: "g" }, { weight: "500g", price: 460, unit: "g" }, { weight: "1kg", price: 880, unit: "g" }]
    },
    {
        id: "sevvalai-malt",
        name_en: "Sevvalai (Red Banana) Malt",
        name_ta: "செவ்வாழை மால்ட்",
        category: "malts",
        basePrice: 300,
        description_en: "Traditional red banana malt for instant energy and strength. Highly nutritious.",
        description_ta: "உடனடி ஆற்றல் மற்றும் வலிமைக்கான பாரம்பரிய செவ்வாழை மால்ட்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Red Banana", "Jaggery", "Cardamom", "Dry Ginger"],
        ingredients_ta: ["செவ்வாழை", "வெல்லம்", "ஏலக்காய்", "சுக்கு"],
        benefits_en: ["Natural energy booster", "Rich in potassium", "Good for digestion", "Strengthens bones"],
        benefits_ta: ["இயற்கை ஆற்றல் அதிகரிப்பான்", "பொட்டாசியம் நிறைந்தது", "செரிமானத்திற்கு நல்லது", "எலும்புகளை வலுப்படுத்துகிறது"],
        storage_en: "Store in an airtight container at room temperature.",
        storage_ta: "அறை வெப்பநிலையில் காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "3 months",
        available: true,
        weightOptions: [{ weight: "250g", price: 300, unit: "g" }, { weight: "500g", price: 580, unit: "g" }, { weight: "1kg", price: 1120, unit: "g" }]
    },
    {
        id: "atthi-malt",
        name_en: "Atthi Malt",
        name_ta: "அத்தி மால்ட்",
        category: "malts",
        basePrice: 320,
        description_en: "Nutritious fig malt for improved digestion and bone health. Traditional Siddha medicine ingredient.",
        description_ta: "மேம்பட்ட செரிமானம் மற்றும் எலும்பு ஆரோக்கியத்திற்கான சத்தான அத்தி மால்ட்.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Dried Figs", "Jaggery", "Cardamom", "Almonds", "Honey"],
        ingredients_ta: ["உலர்ந்த அத்திப்பழம்", "வெல்லம்", "ஏலக்காய்", "பாதாம்", "தேன்"],
        benefits_en: ["Rich in fiber", "Improves digestion", "Good for bone density", "Natural laxative"],
        benefits_ta: ["நார்ச்சத்து நிறைந்தது", "செரிமானத்தை மேம்படுத்துகிறது", "எலும்பு அடர்த்திக்கு நல்லது", "இயற்கை மலமிளக்கி"],
        storage_en: "Store in an airtight container in a cool, dry place.",
        storage_ta: "குளிர்ந்த, உலர்ந்த இடத்தில் காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "3 months",
        available: true,
        weightOptions: [{ weight: "250g", price: 320, unit: "g" }, { weight: "500g", price: 620, unit: "g" }, { weight: "1kg", price: 1200, unit: "g" }]
    },
    {
        id: "satthu-maavu",
        name_en: "Satthu Maavu",
        name_ta: "சத்து மாவு",
        category: "malts",
        basePrice: 350,
        description_en: "Multi-grain health mix powder for complete nutrition. Perfect for babies, children, and adults.",
        description_ta: "முழுமையான ஊட்டச்சத்துக்கான பல தானிய ஆரோக்கிய கலவை பொடி.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Ragi", "Wheat", "Rice", "Moong Dal", "Groundnuts", "Almonds", "Cardamom"],
        ingredients_ta: ["ராகி", "கோதுமை", "அரிசி", "பாசிப்பருப்பு", "வேர்க்கடலை", "பாதாம்", "ஏலக்காய்"],
        benefits_en: ["Complete nutrition", "Rich in protein and fiber", "Good for bone growth", "Boosts immunity"],
        benefits_ta: ["முழுமையான ஊட்டச்சத்து", "புரதம் மற்றும் நார்ச்சத்து நிறைந்தது", "எலும்பு வளர்ச்சிக்கு நல்லது", "நோய் எதிர்ப்பு சக்தியை அதிகரிக்கும்"],
        storage_en: "Store in an airtight container. Keep refrigerated for longer shelf life.",
        storage_ta: "காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "3-4 months",
        available: true,
        weightOptions: [{ weight: "250g", price: 350, unit: "g" }, { weight: "500g", price: 680, unit: "g" }, { weight: "1kg", price: 1320, unit: "g" }]
    },
    {
        id: "curry-leaves-podi",
        name_en: "Curry Leaves Podi",
        name_ta: "கறிவேப்பிலை பொடி",
        category: "podi",
        basePrice: 120,
        description_en: "Aromatic curry leaves podi for hair health and flavor. Essential South Indian condiment.",
        description_ta: "முடி ஆரோக்கியம் மற்றும் சுவைக்கான நறுமணமான கறிவேப்பிலை பொடி.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Curry Leaves", "Urad Dal", "Chana Dal", "Dried Chilli", "Salt", "Sesame Oil"],
        ingredients_ta: ["கறிவேப்பிலை", "உளுந்து", "கடலைப்பருப்பு", "உலர் மிளகாய்", "உப்பு", "நல்லெண்ணெய்"],
        benefits_en: ["Promotes hair growth", "Rich in iron", "Aids digestion", "Natural flavor enhancer"],
        benefits_ta: ["முடி வளர்ச்சியை ஊக்குவிக்கும்", "இரும்பு நிறைந்தது", "செரிமானத்திற்கு உதவுகிறது", "இயற்கை சுவை அதிகரிப்பான்"],
        storage_en: "Store in an airtight container away from moisture.",
        storage_ta: "ஈரப்பதத்திலிருந்து விலக்கி காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "2-3 months",
        available: true,
        weightOptions: [{ weight: "100g", price: 120, unit: "g" }, { weight: "200g", price: 220, unit: "g" }, { weight: "500g", price: 520, unit: "g" }]
    },
    {
        id: "pirandai-podi",
        name_en: "Pirandai Podi",
        name_ta: "பிரண்டை பொடி",
        category: "podi",
        basePrice: 150,
        description_en: "Traditional pirandai podi for bone health and digestion. Ancient Siddha medicine ingredient.",
        description_ta: "எலும்பு ஆரோக்கியம் மற்றும் செரிமானத்திற்கான பாரம்பரிய பிரண்டை பொடி.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Pirandai", "Black Pepper", "Cumin", "Dried Ginger", "Salt"],
        ingredients_ta: ["பிரண்டை", "மிளகு", "சீரகம்", "சுக்கு", "உப்பு"],
        benefits_en: ["Strengthens bones", "Aids digestion", "Rich in calcium", "Traditional medicine"],
        benefits_ta: ["எலும்புகளை வலுப்படுத்துகிறது", "செரிமானத்திற்கு உதவுகிறது", "கால்சியம் நிறைந்தது", "பாரம்பரிய மருத்துவம்"],
        storage_en: "Store in an airtight container in a cool, dry place.",
        storage_ta: "குளிர்ந்த, உலர்ந்த இடத்தில் காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "3-4 months",
        available: true,
        weightOptions: [{ weight: "100g", price: 150, unit: "g" }, { weight: "200g", price: 280, unit: "g" }, { weight: "500g", price: 680, unit: "g" }]
    },
    {
        id: "sundaikai-podi",
        name_en: "Sundaikai Podi",
        name_ta: "சுண்டைக்காய் பொடி",
        category: "podi",
        basePrice: 140,
        description_en: "Traditional sundaikai podi for improved appetite and digestion. Natural deworming properties.",
        description_ta: "மேம்பட்ட பசி மற்றும் செரிமானத்திற்கான பாரம்பரிய சுண்டைக்காய் பொடி.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Sundaikai", "Tamarind", "Chilli", "Salt", "Asafoetida"],
        ingredients_ta: ["சுண்டைக்காய்", "புளி", "மிளகாய்", "உப்பு", "பெருங்காயம்"],
        benefits_en: ["Natural dewormer", "Improves appetite", "Aids digestion", "Rich in antioxidants"],
        benefits_ta: ["இயற்கை புழு நீக்கி", "பசியை மேம்படுத்துகிறது", "செரிமானத்திற்கு உதவுகிறது", "ஆன்டிஆக்ஸிடன்ட்கள் நிறைந்தது"],
        storage_en: "Store in an airtight container away from moisture.",
        storage_ta: "ஈரப்பதத்திலிருந்து விலக்கி காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "3-4 months",
        available: true,
        weightOptions: [{ weight: "100g", price: 140, unit: "g" }, { weight: "200g", price: 260, unit: "g" }, { weight: "500g", price: 620, unit: "g" }]
    },
    {
        id: "paruppu-podi",
        name_en: "Paruppu Podi",
        name_ta: "பருப்பு பொடி",
        category: "podi",
        basePrice: 100,
        description_en: "Classic paruppu podi made with lentils and spices. Perfect accompaniment for rice and ghee.",
        description_ta: "பருப்பு மற்றும் மசாலாக்களுடன் தயாரிக்கப்படும் கிளாசிக் பருப்பு பொடி.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Toor Dal", "Chana Dal", "Urad Dal", "Dried Chilli", "Black Pepper", "Asafoetida"],
        ingredients_ta: ["துவரம் பருப்பு", "கடலைப்பருப்பு", "உளுந்து", "உலர் மிளகாய்", "மிளகு", "பெருங்காயம்"],
        benefits_en: ["High in protein", "Easy to digest", "Traditional flavor", "Nutritious"],
        benefits_ta: ["புரதம் அதிகம்", "எளிதில் செரிக்கும்", "பாரம்பரிய சுவை", "சத்தானது"],
        storage_en: "Store in an airtight container at room temperature.",
        storage_ta: "அறை வெப்பநிலையில் காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "2-3 months",
        available: true,
        weightOptions: [{ weight: "100g", price: 100, unit: "g" }, { weight: "200g", price: 180, unit: "g" }, { weight: "500g", price: 420, unit: "g" }]
    },
    {
        id: "poondu-podi",
        name_en: "Poondu Podi",
        name_ta: "பூண்டு பொடி",
        category: "podi",
        basePrice: 130,
        description_en: "Flavorful garlic podi for enhanced taste and health benefits. Natural immunity booster.",
        description_ta: "மேம்படுத்தப்பட்ட சுவை மற்றும் ஆரோக்கிய நன்மைகளுக்கான சுவையான பூண்டு பொடி.",
        images: ["/placeholder.svg"],
        ingredients_en: ["Garlic", "Dried Chilli", "Urad Dal", "Salt", "Sesame Oil"],
        ingredients_ta: ["பூண்டு", "உலர் மிளகாய்", "உளுந்து", "உப்பு", "நல்லெண்ணெய்"],
        benefits_en: ["Boosts immunity", "Good for heart health", "Natural antibiotic", "Improves digestion"],
        benefits_ta: ["நோய் எதிர்ப்பு சக்தியை அதிகரிக்கும்", "இதய ஆரோக்கியத்திற்கு நல்லது", "இயற்கை ஆன்டிபயாடிக்", "செரிமானத்தை மேம்படுத்துகிறது"],
        storage_en: "Store in an airtight container in a cool place.",
        storage_ta: "குளிர்ந்த இடத்தில் காற்று புகாத கொள்கலனில் சேமிக்கவும்.",
        shelfLife: "2-3 months",
        available: true,
        weightOptions: [{ weight: "100g", price: 130, unit: "g" }, { weight: "200g", price: 240, unit: "g" }, { weight: "500g", price: 580, unit: "g" }]
    }
];

const seedProducts = async () => {
    try {
        await connectDB();

        const existing = await Product.countDocuments();
        if (existing > 0) {
            console.log(`Products collection already has ${existing} documents. Clearing and re-seeding...`);
            await Product.deleteMany({});
        }

        const inserted = await Product.insertMany(products);
        console.log(`✅ Successfully seeded ${inserted.length} products into MongoDB!`);

        process.exit(0);
    } catch (error) {
        console.error('❌ Error seeding products:', error.message);
        process.exit(1);
    }
};

seedProducts();
